[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
csv = "1.1"
diesel = { version = "2.0.0", features = ["postgres", "extras"] }
dotenvy = "0.15"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
reqwest = "0.11.12"
html2text = "0.4.3"
scraper = "0.13.0"