version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080

volumes:
  data:
